name: netZooPy

on:
  release:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: publish-to-conda
        uses: fcakyon/conda-publish-action@v1.3
        with:
          subdir: "conda"
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: "linux osx"
